version: "1.0"
services:
  elasticsearch:
    container_name: elasticsearch-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    environment:
      - "discovery.type=single-node"
      - ELASTIC_PASSWORD=rockyou
    networks:
      - elk-bridge-network
    ports:
      - 9200:9200
  logstash:
    container_name: logstash-container
    image: docker.elastic.co/logstash/logstash:8.15.3
    networks:
      - elk-bridge-network
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    environment:
      - LOG_LEVEL=error
      - ELASTICSEARCH_USER=elastic
      - ELASTICSEARCH_PASSWORD=rockyou
      - ELASTICSEARCH_URL=https://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 5044:5044
  kibana:
    container_name: kibana-container
    image: docker.elastic.co/kibana/kibana:8.15.3
    networks:
      - elk-bridge-network
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
networks:
  elk-bridge-network:
    driver: bridge